$(function() {
	$('.tscx').click(function() {
		$(this).css('color', '#fde9bc')
		$('.zxc').css('color', '#fff')
		$('.xcz').css('color', '#fff')
		$('.cxz').css('color', '#fff')
		$('.box_1').removeClass('none')
		$('.box_2').addClass('none')
		$('.box_3').addClass('none')
		$('.new').addClass('none')
		$('.brd_ig1').removeClass('none').siblings().addClass('none')
	})
	$('.zxc').click(function() {
		$(this).css('color', '#fde9bc')
		$('.tscx').css('color', '#fff')
		$('.xcz').css('color', '#fff')
		$('.cxz').css('color', '#fff')
		$('.box_2').removeClass('none')
		$('.box_1').addClass('none')
		$('.box_3').addClass('none')
		$('.new').addClass('none')
		$('.brd_ig2').removeClass('none').siblings().addClass('none')
	})
	$('.xcz').click(function() {
		$(this).css('color', '#fde9bc')
		$('.zxc').css('color', '#fff')
		$('.tscx').css('color', '#fff')
		$('.cxz').css('color', '#fff')
		$('.box_3').removeClass('none')
		$('.box_1').addClass('none')
		$('.box_2').addClass('none')
		$('.new').addClass('none')
		$('.brd_ig3').removeClass('none').siblings().addClass('none')
	})
	$('.data_details').hover(function() {
		$('.details_ig1').addClass('none').siblings().removeClass('none')
	}, function() {
		$('.details_ig1').removeClass('none').siblings().addClass('none')
	})
})
			$(function() {
				$('.tscx').click(function() {
					$(this).css('color', '#fde9bc')
					$('.zxc').css('color', '#fff')
					$('.xcz').css('color', '#fff')
					$('.cxz').css('color', '#fff')
					// $('.box_1').removeClass('none')
					// $('.box_2').addClass('none')
					// $('.box_3').addClass('none')
					// $('.new').addClass('none')
					$('.brd_ig1').removeClass('none').siblings().addClass('none')
				})
				$('.zxc').click(function() {
					$(this).css('color', '#fde9bc')
					$('.tscx').css('color', '#fff')
					$('.xcz').css('color', '#fff')
					$('.cxz').css('color', '#fff')
					// $('.box_2').removeClass('none')
					// $('.box_1').addClass('none')
					// $('.box_3').addClass('none')
					// $('.new').addClass('none')
					$('.brd_ig2').removeClass('none').siblings().addClass('none')
				})
				$('.xcz').click(function() {
					$(this).css('color', '#fde9bc')
					$('.zxc').css('color', '#fff')
					$('.tscx').css('color', '#fff')
					$('.cxz').css('color', '#fff')
					// $('.box_3').removeClass('none')
					// $('.box_1').addClass('none')
					// $('.box_2').addClass('none')
					// $('.new').addClass('none')
					$('.brd_ig3').removeClass('none').siblings().addClass('none')
				})
				$('.data_details').hover(function() {
					$('.details_ig1').addClass('none').siblings().removeClass('none')
				}, function() {
					$('.details_ig1').removeClass('none').siblings().addClass('none')
				})
			})
